name: WBD
channels:
  - conda-forge
dependencies:
  - python=3.10
  - contextily>=1.4,<2.0
  - dask>=2023.5.0
  - folium=0.18
  - geopandas>=0.13.1,<2.0
  - ipython>=8.29.0,<9.0.0
  - jupyter>=1.0
  - matplotlib>=3.5,<4.0
  - mplleaflet>=0.0.5,<1.0
  - netcdf4>=1.6.4,<2.0
  - numpy>=1.21,<3.0
  - openpyxl>=3,<4
  - pandas>=1.2,<3.0
  - pillow>=11.0.0,<12.0.0
  - pyogrio=0.9
  - rasterio=1.4.2
  - rasterstats=0.19
  - scipy>=1.6,<2.0
  - tqdm>=4.66.1
  - xarray>=2023.1.0
  - xlrd>=2.0.1,<3.0
  - momepy # TODO: kijken of we dit eruit kunnen halen
  - rioxarray=0.18.2
  - geocube
  - networkx
  - pcraster