name: WBD
channels:
  - conda-forge
dependencies:
    - python==3.11.8
    - gdal==3.8.4
    - geopandas==0.14.3
    - jupyter==1.0.0
    - ipython==8.22.2
    - matplotlib==3.8.4
    - fiona==1.9.6
    - netcdf4==1.6.4
    - tqdm==4.66.2
    - scipy==1.13.0
    - pillow==10.3.0
    - lxml==5.1.0
    - fire==0.6.0
    - rasterio==1.3.9
    - rasterstats==0.19.0
    - imod==0.16.0
    - pyogrio=0.7.2
    # dtm2cat dependencies
    - momepy
    - geopandas
    - rioxarray
    - geocube
    - dask
    - networkx
    - pyflwdir
    - pcraster
