name: WBD
channels:
  - conda-forge
  - esri
dependencies:
    - python==3.11.8
    - gdal
    - geopandas
    - jupyter
    - ipython
    - matplotlib
    - fiona
    - netcdf4
    - tqdm
    - scipy
    - pillow
    - lxml
    - fire
    - rasterio
    - rasterstats
    - imod
    - arcgis

